image_a_topic : "/realsense_d435_front_forward/infra1/image_rect_raw"
image_a_transport : "compressed"

image_b_topic : "/realsense_d435_front_forward/infra2/image_rect_raw"
image_b_transport : "compressed"

# auxiliary inputs
input_imu_topic : "/sensors/imu"
input_body_pose_topic : "/state_estimator_pronto/pose"

# output
output_using_imu_time : false
output_body_pose_topic : "/fovis/pose_in_odom"
output_tf_frame : "base_fovis"

# 0 cfg file. 1 IMU r & p. 2 using a pose topic
initial_pose_mode : 2
# if above is 0, then use this position and rpy (degrees) in init
initial_position : [0,0,0]
initial_rpy : [0,0,0]

extrapolate_when_vo_fails : false

# 0: older. 1: well used on MultiSense. 2: used on MultiSense, higher fps and real time
which_vo_options : 2

verbose : false
publish_feature_analysis : true
write_pose_to_file : false

